### ISSUE TITLE
Document the userMenu option 

### ISSUE THREAD

**Issue by ValentinnDimitroff** [ValentinnDimitroff/ra-auth-ui#15]
# Summary
Now that we've added a way to pass a `userMenu`  to the `AuthAdmin` component we need to document the usage and the different use case scenarios. 
Also let's start building a Table of content section.

# Tasks
- [ ] Add the `userMenu` prop to the `Available Props` table with the sufficient description in each column
- [ ] Add a detailed section below featuing:
   - [ ] code example
   - [ ] notes on how to apply it in cases where there is already a custom `Layout` / `AppBar` and how to use the connected Auth versions of these components
- [ ] Add ToC section featuring anchor links to all the below sections
