### ISSUE TITLE
Refactor the profilePage prop

### ISSUE THREAD

**Issue by ValentinnDimitroff** [ValentinnDimitroff/ra-auth-ui#16]
# Summary
The current profile page is not migrated properly to the new version of react-admin. We need to refactor it and also change the implementation to feature easier customisation. 

# Tasks
- [ ] Make the `profilePage` props work in three possible modes
   - [x] default value should be `true` - in such case we should use the default `<ProfilePage />` component
   - [x] `false` boolean value - this indicated that no profile page is going to be shown and we should omit the entry in the `userMenu`
   - [ ] it should support a custom component passed - this should still add the entry in the `userMenu` but the profile page route should load this component instead of the default one
 - [ ] Add a link to the profile page route in the `userMenu` in case the prop has value different from `false`
 - [ ] Include a custom `noLayout` route inside the `CustomRoutes` in `<AuthAdmin />` component for the profile page in case it is enabled
 
 # Extract page's logic to authProvider verbs
 - [ ] Add new verbs for each action on the profile page
 - [ ] Inside the profile page call all business logic through the `authProvider` 
 - [ ] Add example in the demo project
 - [ ] Document all the above changes
