### ISSUE TITLE
Password rules validation 

### ISSUE THREAD

**Issue by ValentinnDimitroff** [ValentinnDimitroff/ra-auth-ui#18]
# Summary
Similarly to the way IdentityAspCore is configured, we want to allow the developers to tell `<AuthAdmin/>` what password rules are required. We should also allow them to add rules of their own.

Inspiration:
<img width="408" alt="image" src="https://github.com/user-attachments/assets/73cd26e1-bb1b-4ffd-a450-5a4aa537e3a4">

# Tasks
- [ ] Add a new prop called `passwordRules`
- [ ] Prepare a default value which should replicate the rules in the screenshots above
- [ ] Visualize all the rules on the `SignUp` and `ResetPassword` pages
   - [ ] initialize all the rules with a negative icon (e.g. a red cross) 
   - [ ] switch each rule's icon to a green tick on rule passed
- [ ] Implement validation methods and a extract them in way that's easy to render on each change

Notes: 
- Experiment with utlizing the new react-adimin's `<Form/>` component and featuring native input components. If this is viable we can get use of the `validate` prop on each input component and implement validators according the react-admin.
- Search for examples or another lib to represent the validation state in the UI (e.g. [mui-password-checklist](https://github.com/tiavina-mika/mui-password-checklist/tree/main/src)
