### ISSUE TITLE
Describe the possibility  for overriding authRoutes

### ISSUE THREAD

**Issue by ValentinnDimitroff** [ValentinnDimitroff/ra-auth-ui#21]
# Summary 
Add section in the Readme on the customization opportunities of the `authRoutes` prop.

# Tasks
- [ ] Show overriding of a route and keeping the default component
- [ ] Show overriding of the component and keeping the default route
- [ ] Make sure all pages are exported and accessible from the library
- [ ] Make sure the `defaultAuthRoutes` are also exported and accessible
